version: '3'
services:
  psql:
    image: postgres:13
    container_name: psql
    volumes:
      - data-web-psql:/var/lib/postgresql/data/
    restart: always
    environment:
      POSTGRES_PASSWORD: "test"
      POSTGRES_USER: "test"
    ports:
      - "5433:5432"
  django:
    build: .
    container_name: django
    stdin_open: true
    tty: true
    volumes:
      - ./static:/www/app/static
      - ./src:/www/src/
    depends_on:
      - psql
    ports:
      - "8000:8000"
    environment:
      DB_HOST: psql
      DB_PORT: 5432
      DATABASE_NAME: "test"
      DATABASE_USER: "test"
      DATABASE_PASSWORD: "test"
      API_KEY_FIXER: "25772f2f83eae376dc4e972fb7fc2950f1979853"
      DJANGO_ENV: "prod"

volumes:
  data-web-psql:
